apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv
  namespace: infrastructure
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.96.64.0
    path: "/"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: testclaim
  namespace: infrastructure
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
  volumeName: "test-pv"
---
kind: Pod
apiVersion: v1
metadata:
  name: write-pod
  namespace: infrastructure
spec:
  containers:
  - name: write-pod
    image: nginx
    volumeMounts:
      - name: nfs-pvc
        mountPath: "/"
  volumes:
    - name: nfs-pvc
      persistentVolumeClaim:
        claimName: testclaim